# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: "windows-latest"
  name: Testpool
  
jobs:
- job: RunPowerShellScript
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: 'C:\Users\tkohlert\Desktop\Powershell.ps1'
      arguments: ''
      errorActionPreference: 'stop'
      failOnStderr: true
 
 