

trigger:
- master

pool:
  name: Testpool
  
jobs:

- job: 'AnalyseXML'
  displayName: 'AnalyseXML'
  steps:
  - powershell: .\tools\ci\scripts\Unittest\XML_Analysis.ps1 -ResultPath $env:BUILD_BINARIESDIRECTORY
    env:
      BUILD_BINARIESDIRECTORY: $Build.BinariesDirectory

   
    