# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Testpool
  
jobs:

- job: 'Debug'
  displayName: 'Printing debug variables'
  steps:
  - powershell: |
      Write-Host "Build.SourcesDirectory is $env:BUILD_SOURCESDIRECTORY"
      Write-Host "Build.BinariesDirectory is $env:BUILD_BINARIESDIRECTORY"
      Write-Host "Agent.HomeDirectory is $env:AGENT_HOMEDIRECTORY"
    displayName: 'printing predefined variables'
    env:
      BUILD_SOURCESDIRECTORY: $Build.SourcesDirectory
      BUILD_BINARIESDIRECTORY: $Build.BinariesDirectory
      AGENT_HOMEDIRECTORY: $Agent.HomeDirectory
  - script: |
        echo "Current path is:"
        echo %cd%  
    displayName: 'Print Current Path'


# prepare pipeline
- job: 'Preparing'
  displayName: 'Prepare pipeline'
  dependsOn: Debug
  steps:
  # delete Binaries and Temp folders
  - powershell: .\tools\ci\scripts\Prepare\Prepare_Pipeline.ps1 -BinariesFolder $env:BUILD_BINARIESDIRECTORY
    env:
      BUILD_BINARIESDIRECTORY: $Build.BinariesDirectory
    displayName: 'Delete binaries folders'
  - powershell: .\tools\ci\scripts\Unittest\Prepare_Unittests.ps1 -ResultFolder $env:BUILD_BINARIESDIRECTORY
    env:
      BUILD_BINARIESDIRECTORY: $Build.BinariesDirectory
    displayName: 'prepare unittest folders'
 
#======================================================================
# Arranging the testobject and the Unittests
#----------------------------------------------------------------------


- job: 'ExchangeCreate_Project'
  displayName: 'Exchange and create testobject'
  dependsOn: Preparing
  steps:
    # exchange unittest project   brauchen wir das ? 
    - powershell: .\tools\ci\scripts\Prepare\Exchange_otherProject.ps1 -Machinetype UnitTest -SourcesDirectory $env:BUILD_SOURCESDIRECTORY
      env:
        BUILD_SOURCESDIRECTORY: $Build.SourcesDirectory
      displayName: 'Exchange unittest project'
    # create the testobject
  
   # - powershell: .\tools\ci\scripts\Unittest\sccx\sccx_TestObject.ps1 -Workspace $env:BUILD_SOURCESDIRECTORY -sccxPath ".\tools\sccx" -exportPath $env:BUILD_BINARIESDIRECTORY
    #  env:
     #   BUILD_SOURCESDIRECTORY: $Build.SourcesDirectory
      #  BUILD_BINARIESDIRECTORY: $Build.BinariesDirectory
      #displayName: 'Create testobject'



  # compiling the testobject
- job: 'Compiling'
    
  dependsOn: ExchangeCreate_Project
  steps:
    - powershell: |
        .\tools\ci\scripts\Unittest\CompileTestObject.ps1 -Project Basis_UnitTest -ToolPath "C:\BRAutomation" -ToolVersion AS412 -SourcesDirectory $env:BUILD_SOURCESDIRECTORY -BinaryDirectory $env:BUILD_BINARIESDIRECTORY
      env:
        BUILD_SOURCESDIRECTORY: $Build.SourcesDirectory
        BUILD_BINARIESDIRECTORY: $Build.BinariesDirectory
 
 