name: '[PLC BuR] CI Platform'
variables:
#  all available options for buildSimulation: 'None,All,Selective,Wave,Print,Reflow,Transport,Platform'
  buildSimulation: 'None'
trigger:
  branches: 
    include:
     - feature/Platform/*
     - release/Platform/*
    exclude:
     - develop
  paths:
    include: 
       - Logical/Allgemein_Tasks_Basis
       - Logical/Allgemein_Tasks_Optional
       - Logical/Allg_Sequenzer
       - Logical/Lib_Common
       - Logical/Allg_MappMotion
       - Logical/Allg_mappCnc
       - Logical/Allg_ACP10Motion
       - Logical/Vorlagen
       - Physical/Basis_CP1686X
       - Physical/Basis_CP1685
       - Physical/Basis_CP3685
       - tools/ci/pipelines/CI_Platform.yaml
    exclude: 
      - '*.txt'
      - '*.md'
      - '*.exe'
      - '*.ps1'
      - '*.pdf'
      - '*.xlsx'
      - '*.docx'
pool:
  name: 'ErsaOfficePLC'

jobs:
# Selective
- job: 'Selective'
  displayName: 'Selective'
  steps:
  - ${{ if or(contains(variables['buildSimulation'], 'Selective'), contains(variables['buildSimulation'], 'All')) }}: 
    - template: ..\steps\mappMotion\BuildProject_Simulation.yaml
      parameters:
        project: S_VfOne_APC2200
        machinetype: Selectiv
        cputype: 5APC2200_AL04_000
        asversion: AS412
    - template: ..\steps\Publish\Publish.yaml
      parameters:
        project: S_VfOne_APC2200
        machinetype: Selectiv
        cputype: 5APC2200_AL04_000
        packages: Simulation
        projectVersion: 'S5_025_004'
  - ${{ else }}:
    - template: ..\steps\mappMotion\BuildProject_NoPublish.yaml
      parameters:
        project: S_VfOne_APC2200
        machinetype: Selectiv
        cputype: 5APC2200_AL04_000
        asversion: AS412
# Wave
- job: 'Wave'
  displayName: 'Wave'
  steps:
  - ${{ if or(contains(variables['buildSimulation'], 'Wave'), contains(variables['buildSimulation'], 'All')) }}: 
    - template: ..\steps\Standard\BuildProject_Simulation.yaml
      parameters:
        project: Powerflow_Pro_CP1586
        machinetype: Powerflow
        cputype: X20CP1586
        asversion: AS412
    - template: ..\steps\Publish\Publish.yaml
      parameters:
        project: Powerflow_Pro_CP1586
        machinetype: Powerflow
        cputype: X20CP1586
        packages: Simulation
        projectVersion: 'W5_016_007'
  - ${{ else }}:
    - template: ..\steps\Standard\BuildProject_NoPublish.yaml
      parameters:
        project: Powerflow_Pro_CP1586
        machinetype: Powerflow
        cputype: X20CP1586
        asversion: AS412
# Print
- job: 'Print'
  displayName: 'Print'
  steps:
  - ${{ if or(contains(variables['buildSimulation'], 'Print'), contains(variables['buildSimulation'], 'All')) }}: 
    - template: ..\steps\Standard\BuildProject_Simulation.yaml
      parameters:
        project: Versaprint_2_CP1585
        machinetype: Versaprint
        cputype: X20CP1585
        asversion: AS412
    - template: ..\steps\Publish\Publish.yaml
      parameters:
        project: Versaprint_2_CP1585
        machinetype: Versaprint
        cputype: X20CP1585
        packages: Simulation
        projectVersion: 'P5_007_000'
  - ${{ else }}:
    - template: ..\steps\Standard\BuildProject_NoPublish.yaml
      parameters:
        project: Versaprint_2_CP1585
        machinetype: Versaprint
        cputype: X20CP1585
        asversion: AS412
# Reflow
- job: 'Reflow'
  displayName: 'Reflow'
  steps:
  - ${{ if or(contains(variables['buildSimulation'], 'Reflow'), contains(variables['buildSimulation'], 'All')) }}: 
    - template: ..\steps\Standard\BuildProject_Simulation.yaml
      parameters:
        project: R_EXOS_CP3586
        machinetype: Reflow
        cputype: X20CP3586
        asversion: AS412
    - template: ..\steps\Publish\Publish.yaml
      parameters:
        project: R_EXOS_CP3586
        machinetype: Reflow
        cputype: X20CP3586
        packages: Simulation
        projectVersion: 'R5_013_000'
  - ${{ else }}:
    - template: ..\steps\Standard\BuildProject_NoPublish.yaml
      parameters:
        project: R_EXOS_CP3586
        machinetype: Reflow
        cputype: X20CP3586
        asversion: AS412
# Fit --> commented out, as not currently supported 
#- job: 'Fit'
#  displayName: 'Fit'
#  steps:
#  - template: ..\steps\mappMotion\BuildProject_NoPublish.yaml
#    parameters:
#      project: Versafit_CP3586
#      machinetype: Versafit
#      cputype: X20CP3586
#      version: AS412
# Transport
- job: 'Transport'
  displayName: 'Transport'
  steps:
  - ${{ if or(contains(variables['buildSimulation'], 'Transport'), contains(variables['buildSimulation'], 'All')) }}: 
    - template: ..\steps\Standard\BuildProject_Simulation.yaml
      parameters:
        project: Remote_CPU_CP0484_BB52
        machinetype: RemoteCPU
        cputype: X20CP0484
        asversion: AS412
    - template: ..\steps\Publish\Publish.yaml
      parameters:
        project: Remote_CPU_CP0484_BB52
        machinetype: RemoteCPU
        cputype: X20CP0484
        packages: Simulation
        projectVersion: 'T5_003_000'
  - ${{ else }}:
    - template: ..\steps\Standard\BuildProject_NoPublish.yaml
      parameters:
        project: Remote_CPU_CP0484_BB52
        machinetype: RemoteCPU
        cputype: X20CP0484
        asversion: AS412
# Platform
- job: 'Platform'
  displayName: 'Platform'
  steps:
  - ${{ if or(contains(variables['buildSimulation'], 'Platform'), contains(variables['buildSimulation'], 'All')) }}: 
    - template: ..\steps\mappMotion\BuildProject_Simulation.yaml
      parameters:
        project: Basis_CP1686X
        machinetype: template
        cputype: X20CP1686X
        asversion: AS412
    - template: ..\steps\Publish\Publish.yaml
      parameters:
        project: Basis_CP1686X
        machinetype: template
        cputype: X20CP1686X
        packages: Simulation
        projectVersion: 'B5_000_000'
  - ${{ else }}:
    - template: ..\steps\mappMotion\BuildProject_NoPublish.yaml
      parameters:
        project: Basis_CP1686X
        machinetype: template
        cputype: X20CP1686X
        asversion: AS412
# unittest project, will be compiled to be safe that the unittest pipeline won't failed
- job: 'Unittest_configuration'
  displayName: 'configuration of unittest'
  steps:
  - template: ..\steps\Standard\BuildProject_NoPublish.yaml
    parameters:
      project: Basis_UnitTest
      machinetype: UnitTest
      cputype: PC
      asversion: AS412