name: '[PLC BuR] CI Reflow'
variables:
  projectVersion: 'R5_013_001'
trigger: 
  branches:
    include:
     - feature/Reflow/*
     - release/Reflow/*
    exclude:
     - develop
  paths:
    include: 
       - Logical/Reflow
       - Physical/R_EXOS_CP3586
       - Physical/R_EXOS_CP3685
       - Physical/R_HF5_CP3685
    exclude: 
      - '*.txt'
      - '*.md'
      - '*.exe'
      - '*.ps1'
      - '*.pdf'
      - '*.xlsx'
      - '*.docx'
pool:
  name: 'ErsaOfficePLC'
resources:
  repositories:
  - repository: BuR.InstallPackage
    type: git
    name: SPS.Tools/BuR.InstallPackage
    ref: release/PVI4.12

jobs:
- job: 'R_EXOS_CP3586'
  displayName: 'R_EXOS_CP3586'
  steps:
  - template: ..\steps\Standard\BuildProject_RUC_PIP.yaml
    parameters:
      project: R_EXOS_CP3586
      machinetype: Reflow
      cputype: X20CP3586
      asversion: AS412
  - template: ..\steps\Standard\BuildProject_Simulation.yaml
    parameters:
      project: R_EXOS_CP3586
      machinetype: Reflow
      cputype: X20CP3586
      asversion: AS412
  - template: ..\steps\Publish\Publish.yaml
    parameters:
      project: R_EXOS_CP3586
      machinetype: Reflow
      cputype: X20CP3586
      packages: PiP,Simulation,Transfer
      projectVersion: $(projectVersion)

- job: 'R_EXOS_CP3685'
  displayName: 'R_EXOS_CP3685'
  steps:
  - template: ..\steps\Standard\BuildProject_RUC_PIP.yaml
    parameters:
      project: R_EXOS_CP3685
      machinetype: Reflow
      cputype: X20CP3685
      asversion: AS412
  - template: ..\steps\Publish\Publish.yaml
    parameters:
      project: R_EXOS_CP3685
      machinetype: Reflow
      cputype: X20CP3685
      packages: PiP,Transfer
      projectVersion: $(projectVersion)

- job: 'R_HF5_CP3685'
  displayName: 'R_HF5_CP3685'
  steps:
  - template: ..\steps\Standard\BuildProject_RUC_PIP.yaml
    parameters:
      project: R_HF5_CP3685
      machinetype: Reflow
      cputype: X20CP3685
      asversion: AS412
  - template: ..\steps\Standard\BuildProject_Simulation.yaml
    parameters:
      project: R_HF5_CP3685
      machinetype: Reflow
      cputype: X20CP3685
      asversion: AS412
  - template: ..\steps\Publish\Publish.yaml
    parameters:
      project: R_HF5_CP3685
      machinetype: Reflow
      cputype: X20CP3685
      packages: PiP,Simulation,Transfer
      projectVersion: $(projectVersion)

- job: 'Publish_PVI'
  displayName: 'Publish PVI, PILs and bats'
  steps:
  - template: ..\steps\Publish\PVI.yaml